# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="habitat-sim-geodesic",
    version="0.1.3",
    python_requires="==3.*,>=3.6.0",
    author="Erik Wijmans",
    author_email="etw@gatech.edu",
    packages=["habitat_sim_geodesic"],
    package_dir={"": "."},
    install_requires=[
        "cppimport==18.*,>=18.11.8",
        "numba==0.*,>=0.48.0",
        "numpy==1.*,>=1.18.2",
        "numpy-quaternion==2019.*,>=2019.12.11",
        "pybind11<2.6,==2.*,>=2.4.3",
    ],
    extras_require={"dev": ["pytest==5.*,>=5.2.0"]},
    include_package_data=True,
)
